name             'boundary_meter'
maintainer       'Nolan Davidson'
maintainer_email 'nolan.davidson@gmail.com'
license          'All rights reserved'
description      'Installs/Configures boundary_meter'
long_description 'Installs/Configures boundary_meter'
version          '0.2.1'

depends 'chef-sugar'
depends 'yum', '> 3.0'
depends 'apt'
